version: "3.9"

services:
  express_app:
    image: mm-express-app-image
    container_name: mm-express-app
    build:
      context: .
      args:
        ENV_TYPE: prod
        UID: 1000
    command: node app.js
    tty: true
    user: "1000"
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - EXPRESS_PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - caddy_net
  
networks:
  caddy_net:
    external: true
